version: "3.8"

services:
  genesis:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - DEBUG=true
    volumes:
      - ./src:/app
      - ./logs:/app/logs
      - ./.env:/app/.env
    command: uvicorn apps.rest_api.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
    depends_on:
      - db

  # PostgreSQL 数据库服务
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=genesis
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=genesis_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: